name: Build and Push Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Rebuild periodically for security updates/etc
    - cron: '0 0 1 * *'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm/v7]
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      if: github.event_name == 'push' || github.event_name == 'schedule'
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        tags: ghcr.io/${{ github.repository_owner }}/ezshare-sync:latest
        platforms: ${{ matrix.platform }}
        file: ./Dockerfile

    - name: Logout of GitHub Container Registry
      run: docker logout ghcr.io
